server:
  port: 8082

spring:
  application:
    name: note-service
  datasource:
    url: jdbc:mysql://localhost:3306/demo-db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaulthost: http://localhost:8761/eureka