server:
  port: 8081

spring:
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaulthost: http://localhost:8761/eureka